const PluginManager = require('./src/api/index');

(async() =>{
  //const reports = await PluginManager.getReports()
  //const reportsByCountries = await PluginManager.getReportsByCountries('us');
  //const deaths = await PluginManager.getDeaths();
  //const situationsReports = await PluginManager.getSituationReports();
  //const taskforce = await PluginManager.getTaskForceInfoUS();
  //const globalData = await PluginManager.getGlobalData();
  //const testsInUS = await PluginManager.getTestsInUS();
  //const fatalityRateByAge = await PluginManager.getFatalityRateByAge();
  //const fatalityRateBySex = await PluginManager.getFatalityRateBySex();
  //const fatalityRateByComorbidities = await PluginManager.getFatalityRateByComorbidities();
  //const countriesWhereCoronavirusHasSpread = await PluginManager.getCountriesWhereCoronavirusHasSpread();
  //const travelHealthNotices = await PluginManager.getTravelHealthNotices();
  //const getAllCasesInAmerica = await PluginManager.getAllCasesInAmerica();
  //const getAllCasesInEurope = await PluginManager.getAllCasesInEurope();
  //const caseStatusUndeEvalutationInPR = await PluginManager.getCaseStatusUndeEvalutationInPR();
  //const casesInAllUSStates = await PluginManager.getCasesInAllUSStates();
  //const capacityInfoUSHealthFacilities = await PluginManager.getCapacityInfoUSHealthFacilities();
  //const aggregatedFacilityCapacityCounty = await PluginManager.getAggregatedFacilityCapacityCounty();
  //const johnsHopkinsDataDailyReport = await PluginManager.getJohnsHopkinsDataDailyReport();
  //const prGeneralResults = await PluginManager.getPRGeneralResults();
  //const prDataByRegion = await PluginManager.getPRDataByRegion();
  //const prDataBySex = await PluginManager.getPRDataBySex();
  //await PluginManager.downloadReportsToCSV();
  //const indiaCasesByStates = await PluginManager.getIndiaCasesByStates();
  //const spainCasesByCommunities = await PluginManager.getSpainCasesByCommunities();
  //const australiaCasesByStates = await PluginManager.getAustraliaCasesByStates();
  //const canadaCasesByProvincesAndHealthRegion = await PluginManager.getCanadaCasesByProvincesAndHealthRegion();
  //const japanCasesByPrefecture = await PluginManager.getJapanCasesByPrefecture();
  //const getNewZealandCasesByDistrictHealthBoard = await PluginManager.getNewZealandCasesByDistrictHealthBoard();
  //const unitedStateCasesByStates = await PluginManager.getUnitedStateCasesByStates();
  //const getCivicFreedomTracker = await PluginManager.getCivicFreedomTracker();
  //const getGermanyCasesByRegion = await PluginManager.getGermanyCasesByRegion();
  //const getSwedenCasesByRegion = await PluginManager.getSwedenCasesByRegion();
  //const getSlovakiaCasesByDistrict = await PluginManager.getSlovakiaCasesByDistrict();
  //const getPortugalCasesByRegion = await PluginManager.getPortugalCasesByRegion(); 
  //const getPolandCasesByRegion = await PluginManager.getPolandCasesByRegion();
  //const getPalestineCasesByRegion = await PluginManager.getPalestineCasesByRegion();
  //const getNorwayCasesByRegion = await PluginManager.getNorwayCasesByRegion();
  //const getBrazilCasesByRegion = await PluginManager.getBrazilCasesByRegion();
  //const getAlgeriaCasesByRegion = await PluginManager.getAlgeriaCasesByRegion();
  //console.log(JSON.stringify(getAlgeriaCasesByRegion , null , 2));
})();
